globalVariables(c("ABUNDANCE", "ACCESSORIES", "ACCSPGRIDCODE", "ACTIVITYDESC", 
"ADJ_TOTNO", "ADJ_TOTWGT", "airtemp", "ALTERATIONDESC", "AREA", 
"Area Swept by the Net (hectares)", "Areakm2", "Areanmi2", "AUDITJOIN", 
"AUTHOR", "AUX", "bdo", "BDO", "Best Depth (m)", "Best Depth Type", 
"Best Latitude (dd)", "Best Longitude (dd)", "Best Position Type", 
"Best.Depth.Type", "Best.Position.Type", "BGSCODE", "BGSID", 
"BIO_BGS", "biomass", "BIOMASS", "BOT_DEPTH", "BOT_TEMP", "BOTSALIN", 
"bottemp", "BOTTEMP", "bottempmeth", "bottom", "BOTTOM_DEPTH", 
"BOTTOM_SALINITY", "BOTTOM_TEMPERATURE", "BOTTOM_TYPE", "BS", 
"bsalin", "btemp", "BTMCOMPDESC", "CALWT", "catch", "CATCHJOIN", 
"CATCHSEX", "CATCHSUBSAMPLED", "CATCHSUBWEIGHT", "CATCHWEIGHT", 
"CATEGORY", "class", "cnt", "cntcpue", "CNTEXP", "CODE", "COLLECTIONNUMBER", 
"comment", "COMMENTS", "common", "COMMON", "COMMON_NAME", "COMNAME", 
"COMSTAT", "conflict", "cruise", "CRUISE", "Cruise Leg", "CRUISE_NO", 
"Cruise.Leg", "CRUISE6", "CRUISEID", "CRUISEJOIN", "CURNT", "date", 
"DATE", "date.end", "datetime", "DATETIME", "day", "dayl", "depth", 
"DEPTH", "DEPTH_SSTA", "depth.end", "depth.max", "depth.min", 
"depth.start", "depthbottom", "depthend", "DEPTHEND", "depthmax", 
"depthmin", "depthst", "DEPTHSTART", "DEPTHZONE", "depthzone_fathoms", 
"DIST", "distance", "DISTANCE_FISHED", "DMAX", "DMIN", "dtow", 
"DUR", "duration", "DURATION", "E_LATD", "E_LATM", "E_LOND", 
"E_LONM", "effort", "EFFORT", "ELAT", "ELONG", "END_DEPTH", "END_LATITUDE", 
"END_LONGITUDE", "ESTIMATEDLOC", "ETIME", "EVENTNAME", "EVENTTYPEDESCRIPTION", 
"expt", "family", "flag", "FORCE", "gear", "GEAR", "GEAR_DEPTH", 
"GEAR_SIZE", "GEAR_TEMPERATURE", "GEAR_TYPE", "GEARCODE", "geardevice", 
"GEARNAME", "gearsize", "geartype", "genus", "GENUS_BGS", "GOA", 
"haul", "HAUL", "HAUL       ", "Haul Weight (kg)", "HAUL_TYPE", 
"haulid", "HAULJOIN", "HOWD", "HOWS", "Individual Average Weight (kg)", 
"Individual.Average.Weight..kg.", "INVRECID", "ITISSPP", "keep.row", 
"kg", "kingdom", "LASTUPDATED", "lat", "LAT", "lat.deg.end", 
"lat.deg.start", "lat.end", "lat.min.end", "lat.min.start", "lat.start", 
"latend", "latin_name", "latitude", "LATITUDE", "LATITUDEEND", 
"LATITUDESTART", "latstart", "length", "LENGTH", "light", "LIGHTPHASE", 
"LOCATION", "lon", "LON", "lon.deg.end", "lon.deg.start", "lon.end", 
"lon.min.end", "lon.min.start", "lon.start", "lonend", "longitude", 
"LONGITUDE", "LONGITUDEEND", "LONGITUDESTART", "lonstart", "MARKET", 
"MESH_SIZE", "meshsize", "MIN_FISH", "MISSION", "MO_DAY_YR", 
"month", "monthl", "MRRI_CODE", "mtch.src", "N", "nafo", "name", 
"NBRREP", "NET_HEIGHT", "NET_MEASURED", "NET_WIDTH", "num", "NUMBER_FISH", 
"NUMBERTOTAL", "NUMCPUE", "NUMLEN", "OP", "operation", "order", 
"ORGWTUNITS", "P_STA_NO", "PERFORMANCE", "phylum", "Picture", 
"posmethod", "PRECIPITATION", "PRESSURE", "PROJECTAGENCY", "PROJECTNAME", 
"recordtype", "ref", "reg", "REGION", "REMARKS", "REVISION", 
"S_LATD", "S_LATM", "S_LOND", "S_LONM", "salin_bottom", "SALINITYBOTTOM", 
"SALINITYSURFACE", "SAMPWGT", "SCIENTIFIC", "SCINAME", "SDATE", 
"sdo", "SDO", "sea", "season", "SEASON", "SEDSIZEDESC", "SELECT_BGS", 
"set", "SETNO", "settype", "SID", "SIZE_CLASS", "SLAT", "SLONG", 
"SPEC_BGS", "species", "Species", "SPECIES_CODE", "SPECIES_NAME", 
"species.code", "SPECIESCODE", "SPECIESCOMMONNAME", "SPECIESSCIENTIFICNAME", 
"SPECIESSUBWEIGHT", "SPECIESTOTALWEIGHT", "SPECIESWGTPROCESSED", 
"SPECSTATUSDESCRIPTION", "SPEED", "spp", "sppcode", "ssalin", 
"START_DEPTH", "START_LATITUDE", "START_LONGITUDE", "START_TIME", 
"station", "STATION", "station.comment", "STATIONCODE", "STATIONID", 
"stemp", "stratarea", "stratarea_nmi2", "stratum", "STRATUM", 
"stratumarea", "subphylum", "SUBSAMPLE", "SUBSAMPLE_CODE", "superclass", 
"SURF_TEMP", "SURFACE_TEMPERATURE", "SURFSALIN", "surftemp", 
"SURFTEMP", "Survey", "Survey Cycle", "survey.name", "SVSPP", 
"SVVESSEL", "t_bottom", "t_surface", "tax.src", "tax.src2", "taxLvl", 
"TAXONOMIC", "tbl.row", "TEMP_BOT", "TEMP_SSURF", "TEMPAIR", 
"TEMPBOTTOM", "temperature", "Temperature At the Gear (degs C)", 
"TEMPSURFACE", "time", "TIME", "TIME_MIL", "TIME_ZN", "timel", 
"TIMESTART", "timezone", "TIMEZONE", "TITLE", "towarea", "towdistance", 
"towduration", "towID", "towspeed", "TOWTYPETEXT", "Trawl Date", 
"Trawl Duration (min)", "Trawl Id", "Trawl Performance", "Trawl Start Time", 
"Trawl.Performance", "trawlableunits", "trip", "trophicDiet", 
"trophicLevel", "trophicLevel.se", "trophicOrig", "TYPE", "unitarea", 
"unknown", "val.src", "vessel", "Vessel", "VESSEL", "VESSEL_SPD", 
"VESSELNAME", "VOUCHER", "WATERLVLDESC", "WAVEHEIGHT", "WC", 
"WEATHERDESC", "website", "website2", "weight", "WEIGHT", "WEIGHTMETHODDESC", 
"wgt", "WIND", "winddir", "WINDDIRECTION", "windforce", "WINDSPEED", 
"WIRE_LENGTH", "wtcpue", "WTCPUE", "year", "YEAR", "yearl"))

# other columns that need to be declared
globalVariables(c("value", "nhid", "V1", "t.fill", "sppCorr", "classification", "strat2", "StratumCode", "survdat", "neus.survdat.raw","neus.spp","neus.station","Series","zippath"))